

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Li\Desktop\Pose6dSolver-pyqt\ui_files\EditProject.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(688, 461)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.layout_dir_root = QtWidgets.QHBoxLayout()
        self.layout_dir_root.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.layout_dir_root.setContentsMargins(-1, -1, -1, 1)
        self.layout_dir_root.setObjectName("layout_dir_root")
        self.label_dir_root = QtWidgets.QLabel(Form)
        self.label_dir_root.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_dir_root.setObjectName("label_dir_root")
        self.layout_dir_root.addWidget(self.label_dir_root)
        self.line_dir_root = QtWidgets.QLineEdit(Form)
        self.line_dir_root.setEnabled(False)
        self.line_dir_root.setObjectName("line_dir_root")
        self.layout_dir_root.addWidget(self.line_dir_root)
        self.gridLayout.addLayout(self.layout_dir_root, 0, 0, 1, 1)
        self.layout_calib_solve = QtWidgets.QHBoxLayout()
        self.layout_calib_solve.setContentsMargins(-1, 1, -1, 4)
        self.layout_calib_solve.setObjectName("layout_calib_solve")
        self.groupbox_calib = QtWidgets.QGroupBox(Form)
        self.groupbox_calib.setObjectName("groupbox_calib")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupbox_calib)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_btns_calib = QtWidgets.QHBoxLayout()
        self.layout_btns_calib.setObjectName("layout_btns_calib")
        self.pushbtn_add_images_calib = QtWidgets.QPushButton(self.groupbox_calib)
        self.pushbtn_add_images_calib.setObjectName("pushbtn_add_images_calib")
        self.layout_btns_calib.addWidget(self.pushbtn_add_images_calib)
        self.verticalLayout.addLayout(self.layout_btns_calib)
        self.layout_unit_length_calib = QtWidgets.QHBoxLayout()
        self.layout_unit_length_calib.setObjectName("layout_unit_length_calib")
        self.label_unit_length_calib = QtWidgets.QLabel(self.groupbox_calib)
        self.label_unit_length_calib.setObjectName("label_unit_length_calib")
        self.layout_unit_length_calib.addWidget(self.label_unit_length_calib)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_unit_length_calib.addItem(spacerItem)
        self.line_unit_length_calib = QtWidgets.QLineEdit(self.groupbox_calib)
        self.line_unit_length_calib.setText("")
        self.line_unit_length_calib.setObjectName("line_unit_length_calib")
        self.layout_unit_length_calib.addWidget(self.line_unit_length_calib)
        self.verticalLayout.addLayout(self.layout_unit_length_calib)
        self.layout_num_cameras_calib = QtWidgets.QHBoxLayout()
        self.layout_num_cameras_calib.setObjectName("layout_num_cameras_calib")
        self.label_num_cameras_calib = QtWidgets.QLabel(self.groupbox_calib)
        self.label_num_cameras_calib.setObjectName("label_num_cameras_calib")
        self.layout_num_cameras_calib.addWidget(self.label_num_cameras_calib)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_num_cameras_calib.addItem(spacerItem1)
        self.line_num_cameras_calib = QtWidgets.QLineEdit(self.groupbox_calib)
        self.line_num_cameras_calib.setEnabled(False)
        self.line_num_cameras_calib.setText("")
        self.line_num_cameras_calib.setObjectName("line_num_cameras_calib")
        self.layout_num_cameras_calib.addWidget(self.line_num_cameras_calib)
        self.verticalLayout.addLayout(self.layout_num_cameras_calib)
        self.layout_num_scenes_calib = QtWidgets.QHBoxLayout()
        self.layout_num_scenes_calib.setObjectName("layout_num_scenes_calib")
        self.label_num_scenes_calib = QtWidgets.QLabel(self.groupbox_calib)
        self.label_num_scenes_calib.setObjectName("label_num_scenes_calib")
        self.layout_num_scenes_calib.addWidget(self.label_num_scenes_calib)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_num_scenes_calib.addItem(spacerItem2)
        self.line_num_scenes_calib = QtWidgets.QLineEdit(self.groupbox_calib)
        self.line_num_scenes_calib.setEnabled(False)
        self.line_num_scenes_calib.setText("")
        self.line_num_scenes_calib.setObjectName("line_num_scenes_calib")
        self.layout_num_scenes_calib.addWidget(self.line_num_scenes_calib)
        self.verticalLayout.addLayout(self.layout_num_scenes_calib)
        self.layout_dir_images_calib = QtWidgets.QHBoxLayout()
        self.layout_dir_images_calib.setObjectName("layout_dir_images_calib")
        self.label_dir_images_calib = QtWidgets.QLabel(self.groupbox_calib)
        self.label_dir_images_calib.setObjectName("label_dir_images_calib")
        self.layout_dir_images_calib.addWidget(self.label_dir_images_calib)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_images_calib.addItem(spacerItem3)
        self.line_dir_images_calib = QtWidgets.QLineEdit(self.groupbox_calib)
        self.line_dir_images_calib.setEnabled(False)
        self.line_dir_images_calib.setText("")
        self.line_dir_images_calib.setObjectName("line_dir_images_calib")
        self.layout_dir_images_calib.addWidget(self.line_dir_images_calib)
        self.verticalLayout.addLayout(self.layout_dir_images_calib)
        self.layout_dir_points2d_calib = QtWidgets.QHBoxLayout()
        self.layout_dir_points2d_calib.setObjectName("layout_dir_points2d_calib")
        self.label_dir_points2d_calib = QtWidgets.QLabel(self.groupbox_calib)
        self.label_dir_points2d_calib.setObjectName("label_dir_points2d_calib")
        self.layout_dir_points2d_calib.addWidget(self.label_dir_points2d_calib)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_points2d_calib.addItem(spacerItem4)
        self.line_dir_points2d_calib = QtWidgets.QLineEdit(self.groupbox_calib)
        self.line_dir_points2d_calib.setEnabled(False)
        self.line_dir_points2d_calib.setText("")
        self.line_dir_points2d_calib.setObjectName("line_dir_points2d_calib")
        self.layout_dir_points2d_calib.addWidget(self.line_dir_points2d_calib)
        self.verticalLayout.addLayout(self.layout_dir_points2d_calib)
        self.layout_points3d_calib = QtWidgets.QHBoxLayout()
        self.layout_points3d_calib.setObjectName("layout_points3d_calib")
        self.label_points3d_calib = QtWidgets.QLabel(self.groupbox_calib)
        self.label_points3d_calib.setObjectName("label_points3d_calib")
        self.layout_points3d_calib.addWidget(self.label_points3d_calib)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_points3d_calib.addItem(spacerItem5)
        self.line_dir_points3d_calib = QtWidgets.QLineEdit(self.groupbox_calib)
        self.line_dir_points3d_calib.setEnabled(False)
        self.line_dir_points3d_calib.setText("")
        self.line_dir_points3d_calib.setObjectName("line_dir_points3d_calib")
        self.layout_points3d_calib.addWidget(self.line_dir_points3d_calib)
        self.verticalLayout.addLayout(self.layout_points3d_calib)
        self.layout_dir_results_calib = QtWidgets.QHBoxLayout()
        self.layout_dir_results_calib.setObjectName("layout_dir_results_calib")
        self.label_dir_results_calib = QtWidgets.QLabel(self.groupbox_calib)
        self.label_dir_results_calib.setObjectName("label_dir_results_calib")
        self.layout_dir_results_calib.addWidget(self.label_dir_results_calib)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_results_calib.addItem(spacerItem6)
        self.line_dir_results_calib = QtWidgets.QLineEdit(self.groupbox_calib)
        self.line_dir_results_calib.setEnabled(False)
        self.line_dir_results_calib.setText("")
        self.line_dir_results_calib.setObjectName("line_dir_results_calib")
        self.layout_dir_results_calib.addWidget(self.line_dir_results_calib)
        self.verticalLayout.addLayout(self.layout_dir_results_calib)
        self.layout_dir_visualize_calib = QtWidgets.QHBoxLayout()
        self.layout_dir_visualize_calib.setObjectName("layout_dir_visualize_calib")
        self.label_dir_visualize_calib = QtWidgets.QLabel(self.groupbox_calib)
        self.label_dir_visualize_calib.setObjectName("label_dir_visualize_calib")
        self.layout_dir_visualize_calib.addWidget(self.label_dir_visualize_calib)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_visualize_calib.addItem(spacerItem7)
        self.line_dir_visualize_calib = QtWidgets.QLineEdit(self.groupbox_calib)
        self.line_dir_visualize_calib.setEnabled(False)
        self.line_dir_visualize_calib.setText("")
        self.line_dir_visualize_calib.setObjectName("line_dir_visualize_calib")
        self.layout_dir_visualize_calib.addWidget(self.line_dir_visualize_calib)
        self.verticalLayout.addLayout(self.layout_dir_visualize_calib)
        self.layout_calib_solve.addWidget(self.groupbox_calib)
        self.groupbox_solve = QtWidgets.QGroupBox(Form)
        self.groupbox_solve.setObjectName("groupbox_solve")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupbox_solve)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_btns_solve = QtWidgets.QHBoxLayout()
        self.layout_btns_solve.setObjectName("layout_btns_solve")
        self.pushbtn_add_images_solve = QtWidgets.QPushButton(self.groupbox_solve)
        self.pushbtn_add_images_solve.setObjectName("pushbtn_add_images_solve")
        self.layout_btns_solve.addWidget(self.pushbtn_add_images_solve)
        self.pushbtn_add_points3d_solve = QtWidgets.QPushButton(self.groupbox_solve)
        self.pushbtn_add_points3d_solve.setObjectName("pushbtn_add_points3d_solve")
        self.layout_btns_solve.addWidget(self.pushbtn_add_points3d_solve)
        self.pushbtn_add_models_solve = QtWidgets.QPushButton(self.groupbox_solve)
        self.pushbtn_add_models_solve.setObjectName("pushbtn_add_models_solve")
        self.layout_btns_solve.addWidget(self.pushbtn_add_models_solve)
        self.verticalLayout_2.addLayout(self.layout_btns_solve)
        self.layout_num_cameras_solve = QtWidgets.QHBoxLayout()
        self.layout_num_cameras_solve.setObjectName("layout_num_cameras_solve")
        self.label_num_cameras_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_num_cameras_solve.setObjectName("label_num_cameras_solve")
        self.layout_num_cameras_solve.addWidget(self.label_num_cameras_solve)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_num_cameras_solve.addItem(spacerItem8)
        self.line_num_cameras_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_num_cameras_solve.setEnabled(False)
        self.line_num_cameras_solve.setText("")
        self.line_num_cameras_solve.setObjectName("line_num_cameras_solve")
        self.layout_num_cameras_solve.addWidget(self.line_num_cameras_solve)
        self.verticalLayout_2.addLayout(self.layout_num_cameras_solve)
        self.layout_num_scenes_solve = QtWidgets.QHBoxLayout()
        self.layout_num_scenes_solve.setObjectName("layout_num_scenes_solve")
        self.label_num_scenes_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_num_scenes_solve.setObjectName("label_num_scenes_solve")
        self.layout_num_scenes_solve.addWidget(self.label_num_scenes_solve)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_num_scenes_solve.addItem(spacerItem9)
        self.line_num_scenes_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_num_scenes_solve.setEnabled(False)
        self.line_num_scenes_solve.setText("")
        self.line_num_scenes_solve.setObjectName("line_num_scenes_solve")
        self.layout_num_scenes_solve.addWidget(self.line_num_scenes_solve)
        self.verticalLayout_2.addLayout(self.layout_num_scenes_solve)
        self.layout_num_points3d_solve = QtWidgets.QHBoxLayout()
        self.layout_num_points3d_solve.setObjectName("layout_num_points3d_solve")
        self.label_num_points3d_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_num_points3d_solve.setObjectName("label_num_points3d_solve")
        self.layout_num_points3d_solve.addWidget(self.label_num_points3d_solve)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_num_points3d_solve.addItem(spacerItem10)
        self.line_num_points3d_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_num_points3d_solve.setEnabled(False)
        self.line_num_points3d_solve.setObjectName("line_num_points3d_solve")
        self.layout_num_points3d_solve.addWidget(self.line_num_points3d_solve)
        self.verticalLayout_2.addLayout(self.layout_num_points3d_solve)
        self.layout_num_models_solve = QtWidgets.QHBoxLayout()
        self.layout_num_models_solve.setObjectName("layout_num_models_solve")
        self.label_num_models_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_num_models_solve.setObjectName("label_num_models_solve")
        self.layout_num_models_solve.addWidget(self.label_num_models_solve)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_num_models_solve.addItem(spacerItem11)
        self.line_num_models_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_num_models_solve.setEnabled(False)
        self.line_num_models_solve.setText("")
        self.line_num_models_solve.setObjectName("line_num_models_solve")
        self.layout_num_models_solve.addWidget(self.line_num_models_solve)
        self.verticalLayout_2.addLayout(self.layout_num_models_solve)
        self.layout_dir_images_solve = QtWidgets.QHBoxLayout()
        self.layout_dir_images_solve.setObjectName("layout_dir_images_solve")
        self.label_dir_images_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_dir_images_solve.setObjectName("label_dir_images_solve")
        self.layout_dir_images_solve.addWidget(self.label_dir_images_solve)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_images_solve.addItem(spacerItem12)
        self.line_dir_images_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_dir_images_solve.setEnabled(False)
        self.line_dir_images_solve.setText("")
        self.line_dir_images_solve.setObjectName("line_dir_images_solve")
        self.layout_dir_images_solve.addWidget(self.line_dir_images_solve)
        self.verticalLayout_2.addLayout(self.layout_dir_images_solve)
        self.layout_dir_points2d_solve = QtWidgets.QHBoxLayout()
        self.layout_dir_points2d_solve.setObjectName("layout_dir_points2d_solve")
        self.label_dir_points2d_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_dir_points2d_solve.setObjectName("label_dir_points2d_solve")
        self.layout_dir_points2d_solve.addWidget(self.label_dir_points2d_solve)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_points2d_solve.addItem(spacerItem13)
        self.line_dir_points2d_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_dir_points2d_solve.setEnabled(False)
        self.line_dir_points2d_solve.setText("")
        self.line_dir_points2d_solve.setObjectName("line_dir_points2d_solve")
        self.layout_dir_points2d_solve.addWidget(self.line_dir_points2d_solve)
        self.verticalLayout_2.addLayout(self.layout_dir_points2d_solve)
        self.layout_dir_points3d_solve = QtWidgets.QHBoxLayout()
        self.layout_dir_points3d_solve.setObjectName("layout_dir_points3d_solve")
        self.label_dir_points3d_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_dir_points3d_solve.setObjectName("label_dir_points3d_solve")
        self.layout_dir_points3d_solve.addWidget(self.label_dir_points3d_solve)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_points3d_solve.addItem(spacerItem14)
        self.line_dir_points3d_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_dir_points3d_solve.setEnabled(False)
        self.line_dir_points3d_solve.setText("")
        self.line_dir_points3d_solve.setObjectName("line_dir_points3d_solve")
        self.layout_dir_points3d_solve.addWidget(self.line_dir_points3d_solve)
        self.verticalLayout_2.addLayout(self.layout_dir_points3d_solve)
        self.layout_dir_models_solve = QtWidgets.QHBoxLayout()
        self.layout_dir_models_solve.setObjectName("layout_dir_models_solve")
        self.label_dir_models_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_dir_models_solve.setObjectName("label_dir_models_solve")
        self.layout_dir_models_solve.addWidget(self.label_dir_models_solve)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_models_solve.addItem(spacerItem15)
        self.line_dir_models_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_dir_models_solve.setEnabled(False)
        self.line_dir_models_solve.setText("")
        self.line_dir_models_solve.setObjectName("line_dir_models_solve")
        self.layout_dir_models_solve.addWidget(self.line_dir_models_solve)
        self.verticalLayout_2.addLayout(self.layout_dir_models_solve)
        self.layout_dir_result_solve = QtWidgets.QHBoxLayout()
        self.layout_dir_result_solve.setObjectName("layout_dir_result_solve")
        self.label_dir_result_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_dir_result_solve.setObjectName("label_dir_result_solve")
        self.layout_dir_result_solve.addWidget(self.label_dir_result_solve)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_result_solve.addItem(spacerItem16)
        self.line_dir_results_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_dir_results_solve.setEnabled(False)
        self.line_dir_results_solve.setText("")
        self.line_dir_results_solve.setObjectName("line_dir_results_solve")
        self.layout_dir_result_solve.addWidget(self.line_dir_results_solve)
        self.verticalLayout_2.addLayout(self.layout_dir_result_solve)
        self.layout_dir_visualize_solve = QtWidgets.QHBoxLayout()
        self.layout_dir_visualize_solve.setObjectName("layout_dir_visualize_solve")
        self.label_dir_visualize_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_dir_visualize_solve.setObjectName("label_dir_visualize_solve")
        self.layout_dir_visualize_solve.addWidget(self.label_dir_visualize_solve)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_visualize_solve.addItem(spacerItem17)
        self.line_dir_visualize_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_dir_visualize_solve.setEnabled(False)
        self.line_dir_visualize_solve.setText("")
        self.line_dir_visualize_solve.setObjectName("line_dir_visualize_solve")
        self.layout_dir_visualize_solve.addWidget(self.line_dir_visualize_solve)
        self.verticalLayout_2.addLayout(self.layout_dir_visualize_solve)
        self.layout_dir_logs_solve = QtWidgets.QHBoxLayout()
        self.layout_dir_logs_solve.setObjectName("layout_dir_logs_solve")
        self.label_dir_logs_solve = QtWidgets.QLabel(self.groupbox_solve)
        self.label_dir_logs_solve.setObjectName("label_dir_logs_solve")
        self.layout_dir_logs_solve.addWidget(self.label_dir_logs_solve)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_dir_logs_solve.addItem(spacerItem18)
        self.line_dir_logs_solve = QtWidgets.QLineEdit(self.groupbox_solve)
        self.line_dir_logs_solve.setEnabled(False)
        self.line_dir_logs_solve.setText("")
        self.line_dir_logs_solve.setObjectName("line_dir_logs_solve")
        self.layout_dir_logs_solve.addWidget(self.line_dir_logs_solve)
        self.verticalLayout_2.addLayout(self.layout_dir_logs_solve)
        self.layout_calib_solve.addWidget(self.groupbox_solve)
        self.gridLayout.addLayout(self.layout_calib_solve, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "编辑工程"))
        self.label_dir_root.setText(_translate("Form", "根路径:"))
        self.groupbox_calib.setTitle(_translate("Form", "标定:"))
        self.pushbtn_add_images_calib.setText(_translate("Form", "添加图像"))
        self.label_unit_length_calib.setText(_translate("Form", "标定架长度(m):"))
        self.label_num_cameras_calib.setText(_translate("Form", "相机数量:"))
        self.label_num_scenes_calib.setText(_translate("Form", "图像数量(单相机):"))
        self.label_dir_images_calib.setText(_translate("Form", "图像路径:"))
        self.label_dir_points2d_calib.setText(_translate("Form", "关键点(2d)路径:"))
        self.label_points3d_calib.setText(_translate("Form", "关键点(3d)路径:"))
        self.label_dir_results_calib.setText(_translate("Form", "标定输出路径:"))
        self.label_dir_visualize_calib.setText(_translate("Form", "可视化输出路径:"))
        self.groupbox_solve.setTitle(_translate("Form", "测量:"))
        self.pushbtn_add_images_solve.setText(_translate("Form", "添加图像"))
        self.pushbtn_add_points3d_solve.setText(_translate("Form", "添加关键点"))
        self.pushbtn_add_models_solve.setText(_translate("Form", "添加模型"))
        self.label_num_cameras_solve.setText(_translate("Form", "相机数量:"))
        self.label_num_scenes_solve.setText(_translate("Form", "图像数量(单相机):"))
        self.label_num_points3d_solve.setText(_translate("Form", "关键点文件数量:"))
        self.label_num_models_solve.setText(_translate("Form", "模型数量:"))
        self.label_dir_images_solve.setText(_translate("Form", "图像路径:"))
        self.label_dir_points2d_solve.setText(_translate("Form", "关键点(2d)路径:"))
        self.label_dir_points3d_solve.setText(_translate("Form", "关键点(3d)路径:"))
        self.label_dir_models_solve.setText(_translate("Form", "模型路径:"))
        self.label_dir_result_solve.setText(_translate("Form", "测量输出路径:"))
        self.label_dir_visualize_solve.setText(_translate("Form", "可视化输出路径:"))
        self.label_dir_logs_solve.setText(_translate("Form", "记录输出路径:"))


